### ISSUE TITLE
Enable & document icon modification

### ISSUE THREAD

**Issue by gregorias** [Gelio/cmp-natdat#2]
Could you consider setting up a custom kind for this source, so that it's possible to customize its icon? [Copilot cmp does it](https://github.com/zbirenbaum/copilot-cmp/blob/72fbaa03695779f8349be3ac54fa8bd77eed3ee3/lua/copilot_cmp/format.lua#L154-L157) and it lets me modify the Copilot icon like so:

```lua
{
	-- Vscode-like pictograms for Neovim LSP completion items.
	"onsails/lspkind.nvim",
	config = function()
		local lspkind = require("lspkind")
		lspkind.init({
			symbol_map = {
				-- This is an Octocat with devicons.
				Copilot = "",
			},
		})
		vim.api.nvim_set_hl(0, "CmpItemKindCopilot", { fg = "#6CC644" })
	end,
	lazy = true,
}
```

**Comment by Gelio** [comment]
Great idea! I have just added it in https://github.com/Gelio/cmp-natdat/pull/3. Let me know if it suits your needs.

It turns out the custom icon is something I was myself missing in the original implementation and I like how it looks now with my config:

![image](https://github.com/Gelio/cmp-natdat/assets/889383/d6350f00-a79e-400c-9941-7e67b23dbf2d)

**Comment by gregorias** [comment]
Works very well. Thank you!
